### ISSUE TITLE
The role is not idempotent with Debian 12

### ISSUE THREAD

**Issue by rjeffman** [linux-system-roles/certificate#216]
The certificate role is not idempotent using Debian 12 on both the controller and managed node.

For details, see discussion after https://github.com/linux-system-roles/certificate/issues/45#issuecomment-1894465030

**Comment by Nihlus** [comment]
After some more testing, it appears that the certificate is actually re-issued every time the role runs. The configuration I'm using looks like this:

```yml
certificate_requests:
  - name: '{{ ipa_certificate_name }}' # something like "HTTP"
    ca: ipa
    dns: '{{ inventory_hostname }}'
    ip: '{{ ansible_host }}'
    principal: '{{ ipa_certificate_principal }}/{{ inventory_hostname }}@{{ ipaserver_realm }}' # something like HTTP/myhost.mydomain.net@MYDOMAIN.NET
    owner: '{{ ipa_certificate_owner }}'
    group: '{{ ipa_certificate_group }}'
    mode: '{{ ipa_certificate_mode }}'
```

```yml
- name: ensure an IPA-issued certificate is present
  include_role:
    name: fedora.linux_system_roles.certificate
    apply:
      become: true
```
It's part of another role that wraps it up with outer configurable options, but that's the gist of the invocation.
